[package]
name = "titans"
authors = ["BASED"]
license = "GPL-3.0"
version = "0.3.0"
edition = "2021"
description = "Blazingly Fast scraper"
keywords = ["command-line", "scraper", "webscraper", "cli", "youtube-downloader"]
repository = "https://github.com/Based-Programmer/titans"

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
isahc = "1.7.2"
url = "2.4.0"
regex = "1.9.3"
serde_json = "1.0.105"
once_cell = "1.18.0"
