[package]
name = "titans"
authors = ["BASED"]
license = "GPL-3.0"
version = "0.2.6"
edition = "2021"
description = "Blazingly Fast scraper"
keywords = ["command-line", "scraper", "webscraper", "cli"]
repository = "https://github.com/Based-Programmer/titans"

[dependencies]
tokio = { version = "1.28.2", features = ["full"] }
isahc = "1.7.2"
reqwest = "0.11.18"
regex = "1.8.4"
once_cell = "1.18.0"
