[package]
name = "titan"
version = "0.2.1"
author = "BASED"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.2", features = ["full"] }
isahc = "1.7.2"
reqwest = "0.11.18"
regex = "1.8.4"
once_cell = "1.18.0"
